Adapting wfx_checks to DRV 2.0 dmesg traces

diff --git a/linux_scripts/wfx_checks b/linux_scripts/wfx_checks
--- a/linux_scripts/wfx_checks
+++ b/linux_scripts/wfx_checks
@@ -227,51 +227,49 @@ else
 	wfx_driver_loaded=$(dmesg | grep "wfx: Silicon Labs")
 	if [ -n "$wfx_driver_loaded" ]; then
 		echo "Startup:  Driver loaded ($wfx_driver_loaded)"
-		wfx_loading=$(dmesg | grep wfx)
-		if [ -n "$wfx_loading" ]; then
-			wfx_startup=$(dmesg | grep wfx | grep "wfx init done")
-			if [ -n "$wfx_startup" ]; then
-				wfx_driver_success=$(ifconfig wlan0)
-				if [ -n "$wfx_driver_success" ]; then
-					echo "Startup:  all OK, WFx part ready to act as wlan0"
-					echo "Startup:  FW $(dmesg | grep WFM | grep Label)"
-					pow=$(dmesg | grep "Power mode")
-					echo "Startup:  $pow"
-					echo "Startup:  current wlan0 status from 'iwconfig wlan0':"
-					echo "$(iwconfig wlan0)"
-				else
-					printf "Startup:  ${RED}Error: WFx part not visible as wlan0${NO}\n"
-					printf "${INV}$(dmesg | grep wfx)${NO}\n"
-					echo "               Look at the complete dmesg to get more details"
-					echo "               Contact Silicon Labs with a capture of the above information for assistance"
-					exit 1
+		wfx_driver_success=$(ip addr show wlan0)
+		echo "Startup:  all OK, WFx part ready to act as wlan0"
+		if [ -n "$wfx_driver_success" ]; then
+			echo "Startup:  Firmware loaded $(dmesg | grep wfx- | grep Firmware)"
+			if [ $(id -u) == 0 ]; then
+				echo "Startup:  Firmware $(grep 'FW label' /sys/kernel/debug/ieee80211/phy0/wfx/status | cut -d\' -f 2)"
+			fi
+			echo "Startup:  current wlan0 status from 'ip addr show wlan0':"
+			echo "$wfx_driver_success"
+			wpa_supplicant=$(ps -few | grep wpa_supplicant | grep -v grep)
+			hostapd=$(ps -few | grep hostapd | grep -v grep)
+			if [ -n "$wpa_supplicant" ]; then
+				echo "Startup:  wpa_supplicant running: $wpa_supplicant"
+				status_sta=$( wpa_cli status )
+				if [ -n "$status_sta" ]; then
+					echo "Startup:  wpa_cli status:"
+					for param in ${status_sta[@]} 
+					do
+						echo "    $param"
+					done
+				fi
+			fi
+			if [ -n "$hostapd" ]; then
+				echo "Startup:  hostapd running: $hostapd"
+				status_ap=$( hostapd_cli status )
+				if [ -n "$status_ap" ]; then
+					echo "Startup:  hostapd_cli status:"
+					for param in ${status_ap[@]} 
+					do
+						echo "    $param"
+				done
 				fi
 			else
-				printf "Startup:  ${RED}Error: WFx part startup failed${NO}\n"
-				wfx_startup_sdio=$(echo $wfx_loading | grep wfx-sdio)
-				wfx_startup_spi=$(echo $wfx_loading | grep wfx-spi)
-				wfx_startup_bus=$(wfx_bus)
-				if [ -n "$wfx_startup_sdio" ]; then
-					if [ "${wfx_startup_bus}" == "spi" ]; then
-						printf "Startup  ${RED}Error: Driver starting as SDIO while bus mode is SPI${NO} ${INV}You need to reboot the Pi if you changed the bus selection${NO}\n"
-					fi
+				if [ ! -n "$wpa_supplicant" ]; then
+					echo "Startup:  no wpa_supplicant or hostapd running (no demo started)"
 				fi
-				if [ -n "$wfx_startup_spi" ]; then
-					if [ "${wfx_startup_bus}" == "sdio" ]; then
-						printf "Startup   ${RED}Error: Driver starting as SPI while configured bus mode is SDIO${NO} ${INV}You need to reboot the Pi if you changed the bus selection${NO}\n"
-					fi
-					printf "Startup:  ${RED}Error: SPI startup failed.${NO}   ${INV}Is there an EVB attached to the Pi, with the bus selection switch set to 'SPI'?${NO}\n"
-				fi
-				wfx_startup_wrong_keyset=$(echo "$wfx_loading" | grep " keyset is incompatible")
-				if [ -n "$wfx_startup_wrong_keyset" ]; then
-						printf "Keyset    ${RED}Error: ($wfx_startup_wrong_keyset)${NO} ${INV}You need to 'sudo wfx_firmware_install' the correct keyset for your part${NO}\n"
-				fi
-				printf "== wfx dmesg information:\n"
-				printf "${INV}$(dmesg | grep wfx)${NO}\n"
-				printf "               Look at the complete dmesg to get more details\n"
-				printf "               Contact Silicon Labs with a capture of the above information for assistance\n"
-				exit 1
 			fi
+		else
+			printf "Startup:  ${RED}Error: WFx part not visible as wlan0${NO}\n"
+			printf "${INV}$(dmesg | grep wfx)${NO}\n"
+			echo "               Look at the complete dmesg to get more details"
+			echo "               Consult the WFx documentation for information on error messages"
+			exit 1
 		fi
 	else
 		echo "Startup:  Waiting for user to use 'sudo wfx_driver_reload' to load the driver"
