Replace wfx_driver_* by wfx_driver_compile

diff --git a/linux_scripts/driver/wfx_driver_compile b/linux_scripts/driver/wfx_driver_compile
--- a/linux_scripts/driver/wfx_driver_compile
+++ b/linux_scripts/driver/wfx_driver_compile
@@ -1,102 +1,27 @@
 #!/bin/bash
 
 . wfx_set_env
-check_root
+check_no_root
 
-if [ -z ${1} ];
-then
-	echo "No WFX driver selected, listing possible driver sources..."
-	echo "You can proceed with:"
-	echo "   wfx_driver_compile <driver> ; wfx_use_driver <driver> for any of the following versions:"
-	echo "   NB: Will not work with old-style drivers, prior to DRV1.4"
-	. wfx_driver_sources
-	exit 1
-else
-	. wfx_driver_sources "quiet"
-	DRV=${1}
+if [ ! -d "$GITHUB_DRIVER_PATH" ]; then
+    echo "Cannot find directory $GITHUB_DRIVER_PATH" >&2
+    exit 1
 fi
 
-source_match=0
-git_source=0
-local_source=0
-
-for tag in ${GIT_DRIVER_TAGS}; do
-	if [ "${tag}" = "${DRV}" ]; then
-		echo " ${DRV} found in git driver tags"
-		source_match=1
-		git_source=1
-		# Create STORED_DRIVERS_SOURCES_PATH if not already existing
-		if [ ! -d ${STORED_DRIVERS_SOURCES_PATH} ]; then
-			mkdir -p ${STORED_DRIVERS_SOURCES_PATH}
-		fi
-		set -ex
-		mkdir -p ${STORED_DRIVERS_SOURCES_PATH}/${DRV}
-		# Checkout git tag, and copy files to STORED_DRIVERS_SOURCES_PATH
-		git -C ${GITHUB_DRIVER_PATH}/ checkout ${DRV}
-		cp -rf ${GITHUB_DRIVER_PATH}/wfx/* ${STORED_DRIVERS_SOURCES_PATH}/${DRV}
-		COMPILE_PATH=${STORED_DRIVERS_SOURCES_PATH}/${DRV}
-		set +ex
-	fi
-done
-
-for folder in ${STORED_LOCAL_SOURCES}; do
-	if [ "${folder}" = "${DRV}" ]; then
-		echo " ${DRV} found in local sources tags"
-		source_match=1
-		local_source=1
-		COMPILE_PATH=${STORED_LOCAL_SOURCES}/${DRV}
-	fi
-done
-
-if [ $source_match -eq 0 ]; then
-	echo "${DRV} not found in git tags or local folders."
-	echo "Valid values are:"
-	. wfx_driver_sources
-	exit 1
+if [ $# -gt 0 ]; then
+    if ! git -C $GITHUB_DRIVER_PATH checkout $1; then
+        echo "Cannot get tag $1" >&2
+        echo "Possible tags:"
+        git -C $GITHUB_DRIVER_PATH tag | sed 's/^/  /'
+        exit 1
+    fi
 fi
 
-if [ -d ${COMPILE_PATH} ]; then
-	echo "the selected ${DRV} driver exists in ${COMPILE_PATH}"
-	match=1
-	LOCAL_PWD=$(pwd)
-	set -ex
-	# Compile driver
-	cd ${COMPILE_PATH}
-	make clean modules
-	# Create kernel/tag directory
-	KO_PATH=${STORED_DRIVERS_PATH}/${kernel}/${DRV}
-	mkdir -p ${KO_PATH}
-	# Move .ko to kernel directory
-	mv *.ko ${KO_PATH}
-	MODULE="wfx.ko"
-	set +ex
-fi
+DRIVER_VER=$(git -C $GITHUB_DRIVER_PATH describe --tags --dirty)
+KERNEL_VER=$(uname -r)
 
-if [ -d ${KO_PATH} ];
-then
-	if [ -z MODULE ];
-	then
-		echo "${KO_PATH} directory exists, but doesn't contain WFX modules (.ko)!"
-		echo "  Please check the content of this directory before proceeding!"
-		echo "  You may need to use"
-		echo "    wfx_compile_driver <path>"
-		echo "  to compile the driver first"
-	else
-		set -ex
-		# Remove previous link
-		rm -fr /lib/modules/${kernel}/extra
-		# Create link from 'extra' to our new module folder
-		ln -s -f ${KO_PATH}   /lib/modules/${kernel}/extra
-		depmod -a | grep wfx
-		modinfo wfx -v
-		set -ex
-	fi
-else
-	echo "${KO_PATH} directory doesn't exist! Please use one of the following values:"
-	wfx_drivers
-fi
-
-printf "\ndriver currently pointing at\n"
-drv_ln=$(realpath /lib/modules/${kernel}/extra)
-echo ${drv_ln}
-ls -al ${drv_ln}/*.ko
+printf "Installing driver %s for kernel %s\n" "$DRIVER_VER" "$KERNEL_VER"
+set -ex
+make -C $GITHUB_DRIVER_PATH
+sudo make -C $GITHUB_DRIVER_PATH install
+sudo depmod -w
