fix(wfx_test_agent): refactor unimplemented init functions
The initialization environment and `run_as_root` function are not
defined anywhere in- or outside the file, which makes the script fail.
Since the intended purpose was to make the script run as root, refactor
them to achieve that purpose.

diff --git a/test-feature/wfx_test_agent b/test-feature/wfx_test_agent
--- a/test-feature/wfx_test_agent
+++ b/test-feature/wfx_test_agent
@@ -2,8 +2,10 @@
 # Copyright (c) 2019, Silicon Laboratories
 # See license terms contained in COPYING file
 
-. wfx_set_env
-run_as_root
+if [ "$(id -u)" -ne 0 ]; then
+  echo "ERROR: This script must be run as root" >&2
+  exit 1
+fi
 
 USAGE="Usage: $(basename $0) OPTION
 
