Add echos and wait for DHCP lease too in wfx_sta

diff --git a/scripts/wfx_sta b/scripts/wfx_sta
--- a/scripts/wfx_sta
+++ b/scripts/wfx_sta
@@ -63,14 +63,15 @@ wpa_cli_run()
 
 check_interface "$INTERFACE"
 
-# Enable DHCP client on this interface
+echo "Configuring dhcpcd"
 if [ "$DHCP" = "true" ]; then
-    dhcpcd --rebind "$INTERFACE"
+    ip addr flush dev "$INTERFACE"
+    dhcpcd --rebind "$INTERFACE" 2>/dev/null
 else
-    dhcpcd --release "$INTERFACE"
+    dhcpcd --release "$INTERFACE" 2>/dev/null
 fi
 
-# Start wpa_supplicant
+echo "Starting  wpa_supplicant"
 killall --quiet --wait hostapd wpa_supplicant || true
 if [ -z "$CONF" ]; then
     WPA_ARGS="-C /var/run/wpa_supplicant"
@@ -79,7 +80,7 @@ else
 fi
 wpa_supplicant -i "$INTERFACE" -Bs $WPA_ARGS
 
-# Connect
+echo "Setting up connection"
 if [ ! -z "$SSID" ]; then
     wpa_cli_run flush
     wpa_cli_run add_network
@@ -91,14 +92,22 @@ if [ ! -z "$SSID" ]; then
     fi
     wpa_cli_run select_network 0
 
-    # Wait 10s for connection
-    for n in {1..10}; do
+    echo "Waiting for connection"
+    for n in {1..20}; do
         sleep 1
-        if wpa_cli -i $INTERFACE status | grep wpa_state | grep -q COMPLETED; then
-            echo "Associated"
-            exit 0
+        STATUS=$(wpa_cli -i $INTERFACE status)
+        if echo "$STATUS" | grep wpa_state | grep -q COMPLETED; then
+            if [ "$DHCP" = "true" ]; then
+                if echo "$STATUS" | grep -q ip_address; then
+                    echo "Associated and DHCP lease obtained"
+                    exit 0
+                fi
+            else
+                echo "Associated"
+                exit 0
+            fi
         fi
     done
-    echo "ERROR: Association timeout" >&2
+    echo "ERROR: Association or DHCP timeout" >&2
     exit 1
 fi
