Capitalize error message

diff --git a/demos/wfx_demo_station b/demos/wfx_demo_station
--- a/demos/wfx_demo_station
+++ b/demos/wfx_demo_station
@@ -31,7 +31,7 @@ lighttpd -f "$LIGHTTPD_CONF"
 if [ "$DISPLAY" != '' ]; then
     sudo -u pi wpa_gui & disown
 else
-    echo "error: wpa_gui needs a display" >&2
+    echo "ERROR: wpa_gui needs a display" >&2
     exit 1
 fi
 echo "Success"
diff --git a/linux_scripts/driver/wfx_driver_install b/linux_scripts/driver/wfx_driver_install
--- a/linux_scripts/driver/wfx_driver_install
+++ b/linux_scripts/driver/wfx_driver_install
@@ -6,13 +6,13 @@
 check_no_root
 
 if [ ! -d "$GITHUB_DRIVER_PATH" ]; then
-    echo "error: cannot find directory $GITHUB_DRIVER_PATH" >&2
+    echo "ERROR: cannot find directory $GITHUB_DRIVER_PATH" >&2
     exit 1
 fi
 
 if [ $# -gt 0 ]; then
     if ! git -C $GITHUB_DRIVER_PATH checkout $1; then
-        echo "error: cannot get tag $1" >&2
+        echo "ERROR: cannot get tag $1" >&2
         echo "Possible tags:"
         git -C $GITHUB_DRIVER_PATH tag | sed 's/^/  /'
         exit 1
diff --git a/linux_scripts/firmware/wfx_firmware_install b/linux_scripts/firmware/wfx_firmware_install
--- a/linux_scripts/firmware/wfx_firmware_install
+++ b/linux_scripts/firmware/wfx_firmware_install
@@ -9,13 +9,13 @@ check_root
 DEFAULT_CHIP_KEY=C0
 
 if [ ! -d "$GITHUB_FIRMWARE_PATH" ]; then
-    echo "error: cannot find directory $GITHUB_FIRMWARE_PATH" >&2
+    echo "ERROR: cannot find directory $GITHUB_FIRMWARE_PATH" >&2
     exit 1
 fi
 
 if [ $# -gt 0 ]; then
     if ! git -C $GITHUB_FIRMWARE_PATH checkout $1; then
-        echo "error: cannot get tag $1" >&2
+        echo "ERROR: cannot get tag $1" >&2
         echo "Possible tags:"
         git -C $GITHUB_FIRMWARE_PATH tag | sed 's/^/  /'
         exit 1
diff --git a/linux_scripts/pi/wfx_overlay_compile b/linux_scripts/pi/wfx_overlay_compile
--- a/linux_scripts/pi/wfx_overlay_compile
+++ b/linux_scripts/pi/wfx_overlay_compile
@@ -6,7 +6,7 @@ check_root
 check_rpi
 
 if [ $# -lt 1 ]; then
-    echo "error: expecting at least one argument" >&2
+    echo "ERROR: expecting at least one argument" >&2
     exit 1
 fi
 
@@ -17,7 +17,7 @@ for f in "$@"; do
     OUTFILE=/boot/overlays/$OUTFILE_BASE
 
     if [ "$INFILE_BASE" = "$OUTFILE_BASE" ]; then
-        echo "error: input file is expected to end with '-overlay.dts'" >&2
+        echo "ERROR: input file is expected to end with '-overlay.dts'" >&2
         exit 1
     fi
 
diff --git a/linux_scripts/wfx_bus b/linux_scripts/wfx_bus
--- a/linux_scripts/wfx_bus
+++ b/linux_scripts/wfx_bus
@@ -8,7 +8,7 @@ check_rpi
 OVERLAY=$(cat /boot/config.txt | grep "^dtoverlay=wfx-")
 case "$OVERLAY" in
     *spi*sdio*|*sdio*spi*)
-        echo "error: SPI and SDIO overlays and both enabled in /boot/config.txt" >&2
+        echo "ERROR: SPI and SDIO overlays and both enabled in /boot/config.txt" >&2
         exit 1
         ;;
     *spi*)
@@ -18,7 +18,7 @@ case "$OVERLAY" in
         echo sdio
         ;;
     *)
-        echo "error: cannot find dtoverlay entry in /boot/config.txt" >&2
+        echo "ERROR: cannot find dtoverlay entry in /boot/config.txt" >&2
         exit 1
         ;;
 esac
