Prefix fatal errors with 'error:'

diff --git a/demos/wfx_demo_sta b/demos/wfx_demo_sta
--- a/demos/wfx_demo_sta
+++ b/demos/wfx_demo_sta
@@ -24,6 +24,6 @@ wpa_supplicant -i "$INTERFACE" -c "$WPA_SUPPLICANT_CONF" -B -s
 if [ "$DISPLAY" != '' ]; then
     sudo -u pi wpa_gui & disown
 else
-    echo "wpa_gui needs a display" >&2
+    echo "error: wpa_gui needs a display" >&2
     exit 1
 fi
diff --git a/linux_overlays/wfx_overlay_compile b/linux_overlays/wfx_overlay_compile
--- a/linux_overlays/wfx_overlay_compile
+++ b/linux_overlays/wfx_overlay_compile
@@ -5,7 +5,7 @@ check_root
 check_rpi
 
 if [ $# -lt 1 ]; then
-    echo "Expecting at least one argument" >&2
+    echo "error: expecting at least one argument" >&2
     exit 1
 fi
 
@@ -16,7 +16,7 @@ for f in "$@"; do
     OUTFILE=/boot/overlays/$OUTFILE_BASE
 
     if [ "$INFILE_BASE" = "$OUTFILE_BASE" ]; then
-        echo "Input file is expected to end with '-overlay.dts'" >&2
+        echo "error: input file is expected to end with '-overlay.dts'" >&2
         exit 1
     fi
 
diff --git a/linux_scripts/low_level/wfx_set_env b/linux_scripts/low_level/wfx_set_env
--- a/linux_scripts/low_level/wfx_set_env
+++ b/linux_scripts/low_level/wfx_set_env
@@ -16,7 +16,7 @@ GITHUB_CONF_PATH="$GITHUB_TOOLS_PATH/conf"
 check_root()
 {
     if [ $(id -u) != 0 ]; then
-        echo "Please run this script as root (running 'sudo $0' should work)" >&2
+        echo "error: please run this script as root (running 'sudo $0' should work)" >&2
         exit 1
     fi
 }
@@ -24,7 +24,7 @@ check_root()
 check_no_root()
 {
     if [ $(id -u) == 0 ]; then
-        echo "Running this script as root is not recommended" >&2
+        echo "error: running this script as root is not recommended" >&2
         exit 1
     fi
 }
@@ -32,7 +32,7 @@ check_no_root()
 check_rpi()
 {
     if ! grep -q 'NAME="Raspbian GNU/Linux"' /etc/os-release; then
-        echo "You must run this script from a Raspberry" >&2
+        echo "error: you must run this script from a Raspberry" >&2
         exit 1
     fi
 }
@@ -41,9 +41,9 @@ check_hat()
 {
     if [ ! -d /proc/device-tree/hat ]; then
         if  grep -q '^dtparam=i2c_vc=on' /boot/config.txt; then
-            echo "Cannot identify board, /proc/device-tree/hat/ does not exist. Empty eeprom?" >&2
+            echo "error: cannot identify board, /proc/device-tree/hat/ does not exist. Empty eeprom?" >&2
         else
-            echo "Cannot identify board, 'dtparam=i2c_vc=on' is not present in /boot/config.txt." >&2
+            echo "error: cannot identify board, 'dtparam=i2c_vc=on' is not present in /boot/config.txt." >&2
         fi
         exit 1
     fi
@@ -56,7 +56,7 @@ kill_check()
         # At least one process was killed, checking for restart
         sleep 2
         if pidof "$@"; then
-            echo "At least one of the process ($@) is still running, exiting" >&2
+            echo "error: at least one of the process ($@) is still running" >&2
             exit 1
         fi
     fi
@@ -65,7 +65,7 @@ kill_check()
 check_interface()
 {
     if ! ip link show "$1" &> /dev/null; then
-	echo "Interface $1 not detected" >&2
-	exit 1
+        echo "error: interface $1 not detected" >&2
+        exit 1
     fi
 }
diff --git a/linux_scripts/pds/wfx_pds_install b/linux_scripts/pds/wfx_pds_install
--- a/linux_scripts/pds/wfx_pds_install
+++ b/linux_scripts/pds/wfx_pds_install
@@ -6,7 +6,7 @@
 check_root
 
 if [ ! -d "$GITHUB_PDS_PATH" ] && ! [ -e "$1" ]; then
-    echo "Cannot find directory $GITHUB_PDS_PATH" >&2
+    echo "error: cannot find directory $GITHUB_PDS_PATH" >&2
     exit 1
 fi
 
@@ -18,14 +18,14 @@ if [ $# -gt 0 ]; then
 else
     BOARD=$(wfx_board)
     if [ -z "$BOARD" ]; then
-        echo "Cannot identify your board" >&2
+        echo "error: cannot identify your board" >&2
         exit 1
     fi
     INFILE=$GITHUB_PDS_PATH/$(wfx_board).pds.in
 fi
 
 if [ ! -e "$INFILE" ]; then
-    echo "Cannot find PDS $INFILE" >&2
+    echo "error: cannot find PDS $INFILE" >&2
     echo "Possible PDS:"
     (cd $GITHUB_PDS_PATH; ls -1 *.pds.in | sed 's/^/  /')
     exit 1
@@ -36,7 +36,7 @@ OUTFILE_BASE=${INFILE_BASE%.pds.in}.pds
 OUTFILE=/lib/firmware/$OUTFILE_BASE
 
 if [ "$INFILE_BASE" = "$OUTFILE_BASE" ]; then
-    echo "Input file is expected to end with '.pds.in'" >&2
+    echo "error: input file is expected to end with '.pds.in'" >&2
     exit 1
 fi
 
diff --git a/linux_scripts/pds/wfx_pds_send b/linux_scripts/pds/wfx_pds_send
--- a/linux_scripts/pds/wfx_pds_send
+++ b/linux_scripts/pds/wfx_pds_send
@@ -6,13 +6,13 @@
 check_root
 
 if [ "$#" != 1 ]; then
-    echo "Wrong number of arguments. One compressed or plain PDS is expected." >&2
+    echo "error: wrong number of arguments. One compressed or plain PDS is expected." >&2
     exit 1
 fi
 
 INFILE=$1
 if ! [ -f "$INFILE" ]; then
-    echo "$INFILE not found" >&2
+    echo "error: $INFILE not found" >&2
     exit 1
 fi
 
