Typo correction in wfx_set_env comment

diff --git a/linux_scripts/low_level/wfx_set_env b/linux_scripts/low_level/wfx_set_env
--- a/linux_scripts/low_level/wfx_set_env
+++ b/linux_scripts/low_level/wfx_set_env
@@ -65,7 +65,7 @@ kill_check()
 check_interface()
 {
     if ! ip link show "$1" &> /dev/null; then
-        echo "ERROR: interface $1 not detected (did your run wfx_driver_reload?)" >&2
+        echo "ERROR: interface $1 not detected (did you run wfx_driver_reload?)" >&2
         exit 1
     fi
 }
