Add status check before installing driver or firmware version

diff --git a/linux_scripts/low_level/wfx_set_env b/linux_scripts/low_level/wfx_set_env
--- a/linux_scripts/low_level/wfx_set_env
+++ b/linux_scripts/low_level/wfx_set_env
@@ -69,3 +69,16 @@ check_interface()
         exit 1
     fi
 }
+
+check_working_clean()
+{
+    REPO_PATH=$1
+    STATUS=$(git -C $REPO_PATH status --porcelain --untracked-files=no)
+    if ! [ -z "$STATUS" ]; then
+	echo "ERROR: the following files where modified in the direcory $REPO_PATH"
+	echo "$STATUS"
+	echo "To DISCARD modifications, run \"git reset --hard\" in this directory"
+	echo "To SAVE modifications, run \"git stash\" in this directory"
+	exit 1
+    fi
+}
