fix program name in check_root()

diff --git a/linux_scripts/low_level/wfx_set_env b/linux_scripts/low_level/wfx_set_env
--- a/linux_scripts/low_level/wfx_set_env
+++ b/linux_scripts/low_level/wfx_set_env
@@ -17,7 +17,7 @@ GITHUB_CONF_PATH="$GITHUB_TOOLS_PATH/conf"
 check_root()
 {
     if [ $(id -u) != 0 ]; then
-        echo "ERROR: please run this script as root (running 'sudo $0' should work)" >&2
+        echo "ERROR: please run this script as root (running 'sudo $(basename $0)' should work)" >&2
         exit 1
     fi
 }
